AMQP_URI: ${AMQP_URI:"amqp://guest:guest@localhost:5672"}
PRODUCT_IMAGE_ROOT: "http://www.example.com/airship/images"
DB_URIS:
    "orders:Base": ${POSTGRES_URI:"postgres://postgres:postgres@localhost:5432/orders"}
DEFAULT_REDIS_URI: redis://:password@127.0.0.1:6379/7
REDIS_URI: ${REDIS_URI}
max_workers: ${MAX_WORKERS:5}
WEB_SERVER_ADDRESS: 0.0.0.0:${PORT:8000}
WEB_CONCURRENCY: ${MAX_WORKERS:5}
PORT: ${PORT:8000}
